// Generated by gencpp from file robot_t/num_words.msg
// DO NOT EDIT!


#ifndef ROBOT_T_MESSAGE_NUM_WORDS_H
#define ROBOT_T_MESSAGE_NUM_WORDS_H

#include <ros/service_traits.h>


#include <robot_t/num_wordsRequest.h>
#include <robot_t/num_wordsResponse.h>


namespace robot_t
{

struct num_words
{

typedef num_wordsRequest Request;
typedef num_wordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct num_words
} // namespace robot_t


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_t::num_words > {
  static const char* value()
  {
    return "b4834320f090e9235da913886638fb4e";
  }

  static const char* value(const ::robot_t::num_words&) { return value(); }
};

template<>
struct DataType< ::robot_t::num_words > {
  static const char* value()
  {
    return "robot_t/num_words";
  }

  static const char* value(const ::robot_t::num_words&) { return value(); }
};


// service_traits::MD5Sum< ::robot_t::num_wordsRequest> should match
// service_traits::MD5Sum< ::robot_t::num_words >
template<>
struct MD5Sum< ::robot_t::num_wordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_t::num_words >::value();
  }
  static const char* value(const ::robot_t::num_wordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_t::num_wordsRequest> should match
// service_traits::DataType< ::robot_t::num_words >
template<>
struct DataType< ::robot_t::num_wordsRequest>
{
  static const char* value()
  {
    return DataType< ::robot_t::num_words >::value();
  }
  static const char* value(const ::robot_t::num_wordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_t::num_wordsResponse> should match
// service_traits::MD5Sum< ::robot_t::num_words >
template<>
struct MD5Sum< ::robot_t::num_wordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_t::num_words >::value();
  }
  static const char* value(const ::robot_t::num_wordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_t::num_wordsResponse> should match
// service_traits::DataType< ::robot_t::num_words >
template<>
struct DataType< ::robot_t::num_wordsResponse>
{
  static const char* value()
  {
    return DataType< ::robot_t::num_words >::value();
  }
  static const char* value(const ::robot_t::num_wordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_T_MESSAGE_NUM_WORDS_H
