// Generated by gencpp from file robot_t/num_wordsResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_T_MESSAGE_NUM_WORDSRESPONSE_H
#define ROBOT_T_MESSAGE_NUM_WORDSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_t
{
template <class ContainerAllocator>
struct num_wordsResponse_
{
  typedef num_wordsResponse_<ContainerAllocator> Type;

  num_wordsResponse_()
    : count(0)  {
    }
  num_wordsResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::robot_t::num_wordsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_t::num_wordsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct num_wordsResponse_

typedef ::robot_t::num_wordsResponse_<std::allocator<void> > num_wordsResponse;

typedef boost::shared_ptr< ::robot_t::num_wordsResponse > num_wordsResponsePtr;
typedef boost::shared_ptr< ::robot_t::num_wordsResponse const> num_wordsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_t::num_wordsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_t::num_wordsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_t::num_wordsResponse_<ContainerAllocator1> & lhs, const ::robot_t::num_wordsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_t::num_wordsResponse_<ContainerAllocator1> & lhs, const ::robot_t::num_wordsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_t

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_t::num_wordsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_t::num_wordsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_t::num_wordsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_t::num_wordsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_t::num_wordsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_t::num_wordsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_t::num_wordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::robot_t::num_wordsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_t::num_wordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_t/num_wordsResponse";
  }

  static const char* value(const ::robot_t::num_wordsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_t::num_wordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 count\n"
"\n"
;
  }

  static const char* value(const ::robot_t::num_wordsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_t::num_wordsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_wordsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_t::num_wordsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_t::num_wordsResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_T_MESSAGE_NUM_WORDSRESPONSE_H
